-- AQUI SERÃO DEFINIDAS AS TABELAS DO BANCO DE DADOS

CREATE TABLE ORGANIZACAO (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME varchar(100) NOT NULL,
    TIPO CHAR(10) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    
    -- CHECK (TIPO == 1 OR TIPO == 2 OR TIPO == 3),
    
    CONSTRAINT PK_ORGANIZACAO PRIMARY KEY (ID),
    CONSTRAINT UK_EMAIL_ORG UNIQUE KEY (EMAIL)
);

CREATE TABLE EVENTO (
    TITULO varchar(50) NOT NULL,
    DESCRICAO varchar(200) NOT NULL,
    LATITUDE DOUBLE NOT NULL,
    LONGITUDE DOUBLE NOT NULL,
    DATA_EVENTO DATETIME NOT NULL,
    ENDERECO varchar(100) NOT NULL,
    CRIADOR INT NOT NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY(TITULO, DATA_EVENTO),
    CONSTRAINT FK_CRIADOR_EVENTO FOREIGN KEY(CRIADOR) REFERENCES ORGANIZACAO(ID) ON DELETE CASCADE
);

CREATE TABLE NOTIFICACAO (
    TITULO varchar(50) NOT NULL,
    DESCRICAO varchar(200) NOT NULL,
    DATA_NOTIFICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CRIADOR INT NOT NULL,
    CONSTRAINT PK_NOTIFICACAO PRIMARY KEY(TITULO, DATA_NOTIFICACAO),
    CONSTRAINT FK_CRIADOR_NOT FOREIGN KEY(CRIADOR) REFERENCES ORGANIZACAO(ID) ON DELETE CASCADE
);

CREATE TABLE TIPO_LOCALIZACAO (
    NOME varchar(100) NOT NULL,
    ICONE varchar(50) ,
    COR CHAR(6) NOT NULL,
    CONSTRAINT PK_TIPO PRIMARY KEY(NOME)
);

CREATE TABLE LOCALIZACAO (
    NOME varchar(100) NOT NULL,
    DESCRICAO varchar(200) NOT NULL,
    TIPO varchar(100) NOT NULL,
    LATITUDE DOUBLE NOT NULL,
    LONGITUDE DOUBLE NOT NULL,

    CONSTRAINT PK_LOCALIZACOES PRIMARY KEY (LATITUDE, LONGITUDE),
    CONSTRAINT FK_TIPO_LOC FOREIGN KEY (TIPO) REFERENCES TIPO_LOCALIZACAO(NOME) ON DELETE CASCADE 
);